todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add/", views.add_todo, name="add"),
    path("save_new_todo", views.save_new_todo, name="save"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("edit/<int:pk>", views.EditView.as_view(), name="edit"),
    path("update/<int:todo_id>", views.update, name="update"),
    path("delete/<int:todo_id>", views.delete, name="delete"),
    path("toggle/<int:todo_id>", views.toggle_completed, name="toggle"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

todo/models.py
from django.db import models
from django.utils import timezone


class Todo(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    is_completed = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True, blank=False)

    def __str__(self) -> str:
        return self.title

todo/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Todo


class IndexView(generic.ListView):
    template_name = "todo/index.html"
    context_object_name = "todos"
    model = Todo


class DetailView(generic.DetailView):
    template_name = "todo/detail.html"
    context_object_name = "current_todo"
    model = Todo


class EditView(generic.DetailView):
    template_name = "todo/edit.html"
    context_object_name = "current_todo"
    model = Todo


def add_todo(request):
    return render(request, "todo/add.html")


def save_new_todo(request):
    title = request.POST["title"].strip()
    content = request.POST["content"].strip()
    if title != "":
        Todo.objects.create(title=title, content=content)
        return redirect(reverse("todo:index"))
    else:
        return render(
            request, "todo/add.html", {"error": "The todo must contain a title"}
        )


def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    new_title = request.POST["title"].strip()

    if new_title != "":
        todo.title = new_title
        todo.content = request.POST["content"].strip()
        todo.save()
        return redirect(reverse("todo:detail", args=(todo_id,)))
    else:
        return render(
            request,
            "todo/edit.html",
            {"current_todo": todo, "error": "The title is empty!"},
        )


def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    return redirect(reverse("todo:index"))


def toggle_completed(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.is_completed = not todo.is_completed
    todo.save()
    return redirect(reverse("todo:index"))

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todo/templates/todo/add.html
{% extends 'todo/base.html' %}

{% block nav_options %}
    <li><button type="submit" form="add-form" class="group flex rounded-lg p-2 font-medium items-center border-2 border-green-500 hover:text-green-400 transition-all">Save
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2 transition-transform group-hover:translate-y-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
          </svg>
    </button></li>
    <li><a href="{% url 'todo:index' %}" class="block rounded-lg p-2 font-medium items-center border-2 border-red-500 hover:text-red-500 transition-all w-20 text-center">Cancel</a></li>  
{% endblock nav_options %}

{% block content %}
    {% if error %} <span class="block text-red-500 font-medium w-full text-center mb-4">{{ error }}</span> {% endif %}
    <form id="add-form" action="{% url 'todo:save' %}" method="post"
        class="flex flex-col px-8 mb-8"
    >
        {% csrf_token %}
        <label class="flex flex-col font-medium text-xl md:text-3xl gap-2">
            Title
            <input 
                type="text" 
                name="title" 
                id="title"
                class="block rounded-lg focus:outline-none border-2
                active:outline-none
                focus:ring-0
                border-blue-500 shadow-blue-300 shadow-md"
            >
        </label>
        <br>
        <label class="flex flex-col font-medium text-xl md:text-3xl gap-2">
            Content
            <textarea name="content" id="content" cols="30" rows="10"
                class="block rounded-lg focus:outline-none border-2 border-blue-500 shadow-blue-300 shadow-md resize-none focus:ring-0"
            ></textarea>
        </label>
    </form>
{% endblock content %}

todo/templates/todo/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
    {% tailwind_css %}
</head>
<body>
    <header class="bg-blue-600 text-white m-2 p-5 rounded-lg shadow-lg shadow-blue-400 mb-8">
        <h1 class="justify-center md:justify-start text-4xl flex font-semibold mb-6">
            TodoApp
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>
        </h1>
        <nav>
            <ul class="flex gap-4 justify-center md:justify-start">
                {% block nav_options %}
                {% endblock nav_options %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

todo/templates/todo/detail.html
{% extends 'todo/base.html' %}  

{% block nav_options %}
    <li>
        <a 
            href="{% url 'todo:index' %}"
            class="block rounded-lg p-2 font-medium items-center border-2 border-red-500 hover:text-red-500 transition-all w-20 text-center"
        >
            Back
        </a>
    </li>
    <li>
        <a 
            href="{% url 'todo:edit' current_todo.id %}"
            class="block w-20 text-center rounded-lg p-2 font-medium items-center border-2 border-green-500 hover:text-green-400 transition-all"
        >
            Edit
        </a>
    </li>
{% endblock nav_options %}

{% block content %}
    <article class="px-8">
        <section class="flex flex-col md:flex-row md:justify-between md:items-center border-b-blue-300 border-b-2 pb-3 gap-3 md:gap-0">
            <p class="flex gap-2 items-center text-4xl font-medium">
                {{ current_todo.title }}
                {% if current_todo.is_completed %}
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500 md:h-8 md:w-8" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                {% endif %}
            </p> 
            <span class="flex gap-2 items-center text-slate-600 text-xl font-medium">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                 {{ current_todo.pub_date|date:"m-d-Y" }} 
            </span>
        </section>
        <section class="bg-slate-200 rounded-lg mt-6 p-6 shadow-md shadow-slate-200 text-md md:text-lg font-medium">
            <p>
                {{ current_todo.content }}
            </p>
        </section>
    </article>
{% endblock content %}

todo/templates/todo/edit.html
{% extends 'todo/base.html' %}

{% block nav_options %}
    <li>
        <button type="submit" form="update-form" class="group flex rounded-lg p-2 font-medium items-center border-2 border-green-500 hover:text-green-400 transition-all">Update
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2 transition-transform group-hover:translate-y-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" /></svg>
    </button>
    </li>
    <li>
        <a 
            href="{% url 'todo:detail' current_todo.id %}"
            class="block rounded-lg p-2 font-medium items-center border-2 border-red-500 hover:text-red-500 transition-all w-20 text-center"
        >
            Cancel
        </a>
    </li>
{% endblock nav_options %}

{% block content %}
{% if error %} <span class="block text-red-500 font-medium w-full text-center mb-4">{{ error }}</span> {% endif %}
<form id="update-form" action="{% url 'todo:update' current_todo.id %}" method="post"
    class="flex flex-col px-8 mb-8"
>
    {% csrf_token %}
    <label class="flex flex-col font-medium text-xl md:text-3xl gap-2">
        Title
        <input 
            type="text" 
            name="title" 
            id="title"
            class="block rounded-lg focus:outline-none border-2
            active:outline-none
            focus:ring-0
            border-blue-500 shadow-blue-300 shadow-md"
            value="{{ current_todo.title.strip }}"
        >
    </label>
    <br>
    <label class="flex flex-col font-medium text-xl md:text-3xl gap-2">
        Content
        <textarea name="content" id="content" cols="30" rows="10"
            class="block rounded-lg focus:outline-none border-2 border-blue-500 shadow-blue-300 shadow-md resize-none focus:ring-0"
        >{{ current_todo.content.strip }}</textarea>
    </label>
</form>
{% endblock content %}

todo/templates/todo/index.html
{% extends 'todo/base.html'%}

{% block nav_options %}
    <li>
        <a 
            href="{% url 'todo:add' %}" 
            class="group flex rounded-lg p-2 font-medium items-center border-2 border-green-500 hover:text-green-400 transition-all"
        >
            New Todo
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2 group-hover:-rotate-45 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
        </a>
    </li>
{% endblock nav_options %}

{% block content %}
    <ul>
        {% for todo in todos %}
            <li class="flex justify-around odd:bg-blue-100 p-3 items-center">
                <a href="{% url 'todo:toggle' todo.id %}">
                    {% if todo.is_completed %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500 md:h-8 md:w-8" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                      </svg>
                    {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-zinc-500 md:h-8 md:w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    {% endif %}</a>
                <a href="{% url 'todo:detail' todo.id %}" class="font-bold text-xl text-slate-700 transition-transform hover:scale-105 md:text-2xl w-20 text-center md:w-32">{{ todo.title|slice:":7" }}</a><a href="{% url 'todo:delete' todo.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-500 md:h-8 md:w-8" viewBox="0 0 20 20" fill="currentColor">
                        <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                      </svg>
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}